/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.PreparedStatement;
import Koneksi.KoneksiDB;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TreeSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author oc
 */
public class bayarbulanan1 extends javax.swing.JFrame {
     public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql, tgl="", tb="";
    /**
     * Creates new form datapenyewa
     */
    public bayarbulanan1() {
       initComponents();
//        this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        KoneksiDB db = new KoneksiDB();
        db.koneksikoskosan();
        con=db.con;
        stat=db.stat;
        rs=db.rs;
        
        TSEWA.setEnabled(false);
       
         
         THARGA.setEnabled(false);
         TIDKAMAR.setEnabled(false);
         TIDPENYEWA.setEnabled(false);
         TBULAN.setEnabled(false);
        jDateChooser1.setEnabled(false);
        tampilDataSewa();
//        tampildatapenyewa();
        loadData ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        pengguna = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELTAMPIL = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TIDKAMAR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        THARGA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        TBULAN = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TSEWA = new javax.swing.JTextField();
        TIDPENYEWA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RGT ");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PENYEWA");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TRANSAKSI");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BAYAR BULANAN");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SEWA KAMAR");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LAPORAN");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BUKTI BAYAR");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/keluar.png"))); // NOI18N
        jLabel21.setText("KELUAR");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 30));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home2.png"))); // NOI18N
        jLabel38.setText("DASHBOARD");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 60));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 40));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 710));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 50, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESIDENCE GARDEN TOWER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        username.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));

        level.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("level");
        level.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelMouseClicked(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, -1));

        pengguna.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        pengguna.setForeground(new java.awt.Color(255, 255, 255));
        pengguna.setText("USERNAME :");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jPanel1.add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        role.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("LEVEL :");
        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 810, 70));

        TABELTAMPIL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABELTAMPIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELTAMPILMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABELTAMPIL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 780, 260));

        jLabel6.setText("ID Sewa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 200, 20));

        jLabel7.setText("Nama Penyewa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, 20));

        TIDKAMAR.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TIDKAMARCaretUpdate(evt);
            }
        });
        TIDKAMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDKAMARActionPerformed(evt);
            }
        });
        getContentPane().add(TIDKAMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 250, 30));

        jLabel10.setText("ID Kamar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 190, 20));

        jLabel11.setText("Bulan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 190, 20));

        THARGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THARGAActionPerformed(evt);
            }
        });
        getContentPane().add(THARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 250, 30));

        jLabel12.setText("Harga");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 190, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 780, 310));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setText("BAYAR BULANAN");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));
        getContentPane().add(TBULAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 250, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TSEWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSEWAActionPerformed(evt);
            }
        });
        jPanel3.add(TSEWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 6, 240, 30));

        TIDPENYEWA.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TIDPENYEWACaretUpdate(evt);
            }
        });
        TIDPENYEWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDPENYEWAActionPerformed(evt);
            }
        });
        jPanel3.add(TIDPENYEWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 56, 240, 30));

        jLabel8.setText("Tanggal Sewa");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 240, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BAYAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 90, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 780, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TSEWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSEWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSEWAActionPerformed

    private void TIDPENYEWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDPENYEWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDPENYEWAActionPerformed

    private void TIDKAMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDKAMARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDKAMARActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
    // Ambil data dari form atau input yang sudah ada
    String idSewa = TSEWA.getText().trim(); // ID sewa
    String namaPenyewa = TIDPENYEWA.getText().trim(); // Nama penyewa
    Date tanggalSewa = jDateChooser1.getDate(); // Tanggal sewa
    String nomorKamar = TIDKAMAR.getText().trim(); // Nomor kamar
    String bulanInput = TBULAN.getText().trim(); // Ambil input bulan (bisa berisi tahun)
    BigDecimal hargaSewa = new BigDecimal(THARGA.getText().trim()); // Harga sewa

    // Cek apakah tanggal sewa kosong
    if (tanggalSewa == null) {
        JOptionPane.showMessageDialog(rootPane, "Tanggal sewa tidak boleh kosong.");
        return;
    }

    // Ekstrak hanya nama bulan (hilangkan tahun jika ada)
    String bulan = bulanInput.split(" ")[0]; // Ambil kata pertama saja (nama bulan)

    // Validasi agar hanya nama bulan yang tersimpan
    if (!bulan.matches("(?i)Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember")) {
        JOptionPane.showMessageDialog(rootPane, "Format bulan tidak valid. Harap masukkan nama bulan dengan benar.");
        return;
    }

    // --- MENAMPILKAN BARCODE TERLEBIH DAHULU ---
    boolean barcodeDitampilkan = false;
    
    try {
        File barcodeFile = new File("C:\\Users\\oc\\OneDrive\\Documents\\NetBeansProjects\\kos-kosan\\src\\icon\\qrpay.jpg");
        
        if (barcodeFile.exists()) {
            Image barcodeImage = ImageIO.read(barcodeFile);

            // Perkecil ukuran barcode
            Image scaledBarcode = barcodeImage.getScaledInstance(200, 200, Image.SCALE_SMOOTH);

            // Menampilkan barcode dalam JOptionPane
            int confirm = JOptionPane.showConfirmDialog(
                rootPane,
                new JLabel(new ImageIcon(scaledBarcode)), 
                "Total Bayar: Rp " + hargaSewa + "\nTekan OK untuk menyimpan.", 
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE
            );

            // Jika user menekan OK, lanjutkan proses penyimpanan
            if (confirm == JOptionPane.OK_OPTION) {
                barcodeDitampilkan = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Penyimpanan dibatalkan oleh pengguna.");
                return; // Hentikan proses jika user membatalkan
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "File barcode tidak ditemukan.");
        }
    } catch (Exception imgEx) {
        JOptionPane.showMessageDialog(rootPane, "Gagal menampilkan barcode: " + imgEx.getMessage());
        return; // Hentikan proses jika gagal menampilkan barcode
    }

    // --- MENYIMPAN DATA SETELAH BARCODE BERHASIL DITAMPILKAN ---
    if (barcodeDitampilkan) {
        // Query untuk menyimpan data ke dalam tbbulanan
        String sql = "INSERT INTO tbbulanan (idsewa, nama_penyewa, tanggalsewa, nokamar, bulan, harga) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";

        // Siapkan Statement
        PreparedStatement stmt = con.prepareStatement(sql);

        // Set parameter untuk query
        stmt.setString(1, idSewa);
        stmt.setString(2, namaPenyewa);
        stmt.setDate(3, new java.sql.Date(tanggalSewa.getTime()));
        stmt.setString(4, nomorKamar);
        stmt.setString(5, bulan); // Hanya nama bulan
        stmt.setBigDecimal(6, hargaSewa);

        // Eksekusi query untuk menyimpan data
        int rowsAffected = stmt.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Gagal menyimpan data.");
        }
    }

} catch (Exception e) {
    // Tangani kesalahan
    JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
}

// Memperbarui tampilan tabel setelah menyimpan
tampilDataSewa();
bersihForm();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TABELTAMPILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELTAMPILMouseClicked
                                            
    int selectedRow = TABELTAMPIL.getSelectedRow();
    if (selectedRow != -1) {
        String idSewa = TABELTAMPIL.getValueAt(selectedRow, 0).toString();
        String namaPenyewa = TABELTAMPIL.getValueAt(selectedRow, 1).toString();
        Date tanggal = (Date) TABELTAMPIL.getValueAt(selectedRow, 2);
        String nomorKamar = TABELTAMPIL.getValueAt(selectedRow, 3).toString();
         String bulan = TABELTAMPIL.getValueAt(selectedRow, 4).toString();
        String harga = TABELTAMPIL.getValueAt(selectedRow, 5).toString();

        // Menampilkan data yang dipilih ke dalam input field
        TSEWA.setText(idSewa);
        TIDPENYEWA.setText(namaPenyewa);
        jDateChooser1.setDate(tanggal);
        TIDKAMAR.setText(nomorKamar);
        TBULAN.setText(bulan);
        THARGA.setText(harga);

        // Memuat data bulan berdasarkan bulan terakhir di `tbbulanan`
        tampilDataSewa();
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_TABELTAMPILMouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        Dashboard pindah = new Dashboard();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameMouseClicked

    private void levelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_levelMouseClicked

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaMouseClicked

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roleMouseClicked

    private void TIDPENYEWACaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TIDPENYEWACaretUpdate
        
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDPENYEWACaretUpdate

    private void TIDKAMARCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TIDKAMARCaretUpdate
                // TODO add your handling code here:
    }//GEN-LAST:event_TIDKAMARCaretUpdate

    private void THARGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THARGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THARGAActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        datapenyewa1 pindah = new datapenyewa1();
        pindah.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        bayarbulanan1 pindah = new bayarbulanan1();
        pindah.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        sewakamar1 pindah = new sewakamar1();
        pindah.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        buktibayar1 pindah = new buktibayar1();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // Membuat instance dari FrameB
        login pindah = new login();

        // Menampilkan pesan konfirmasi
        JOptionPane.showMessageDialog(null, "Anda yakin untuk keluar.");

        // Menutup jendela
        dispose();

        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // Membuat instance dari FrameB
        Dashboard1 pindah = new Dashboard1();
        // Menutup jendela
        dispose();
        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bayarbulanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bayarbulanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bayarbulanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bayarbulanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bayarbulanan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABELTAMPIL;
    private javax.swing.JTextField TBULAN;
    private javax.swing.JTextField THARGA;
    private javax.swing.JTextField TIDKAMAR;
    private javax.swing.JTextField TIDPENYEWA;
    private javax.swing.JTextField TSEWA;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel level;
    private javax.swing.JLabel pengguna;
    private javax.swing.JLabel role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private void bersih() {
   
    // Bersihkan semua JTextField
   
    TIDPENYEWA.setText(""); // Membersihkan TextField ID Penyewa
    TIDKAMAR.setText(""); // Membersihkan TextField ID Kamar
    THARGA.setText(""); 
  }
    
    private void tampilDataSewa() {
    try {
    // Query untuk mengambil data dengan entri terbaru dari tbbulanan
    String sql = "SELECT s.id_sewa, p.nama_penyewa, s.tanggal, s.nomor_kamar, " +
                 "       IFNULL(b.bulan, 'Belum Ada') AS bulan, k.harga_sewa, " +
                 "       CASE " +
                 "           WHEN b.bulan = 'Januari' THEN CONCAT('Februari ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Februari' THEN CONCAT('Maret ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Maret' THEN CONCAT('April ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'April' THEN CONCAT('Mei ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Mei' THEN CONCAT('Juni ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Juni' THEN CONCAT('Juli ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Juli' THEN CONCAT('Agustus ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Agustus' THEN CONCAT('September ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'September' THEN CONCAT('Oktober ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Oktober' THEN CONCAT('November ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'November' THEN CONCAT('Desember ', YEAR(b.created_at)) " +
                 "           WHEN b.bulan = 'Desember' THEN CONCAT('Januari ', YEAR(b.created_at) + 1) " +
                 "           ELSE 'Belum Ada' " +
                 "       END AS bulan_setelah " +
                 "FROM tbsewa s " +
                 "JOIN tbpenyewa p ON s.id_penyewa = p.id_penyewa " +
                 "JOIN tbkamar k ON s.nomor_kamar = k.nomor_kamar " +
                 "LEFT JOIN tbbulanan b ON s.id_sewa = b.idsewa " +
                 "AND b.created_at = (SELECT MAX(b2.created_at) FROM tbbulanan b2 WHERE b2.idsewa = s.id_sewa)";

    // Siapkan Statement
    Statement stmt = con.createStatement();
    
    // Eksekusi query
    ResultSet rs = stmt.executeQuery(sql);

    // Buat model untuk JTable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Sewa");
    model.addColumn("Nama Penyewa");
    model.addColumn("Tanggal Sewa");
    model.addColumn("Nomor Kamar");
    model.addColumn("Bulan Berikutnya");
    model.addColumn("Harga Sewa");

    boolean adaData = false; // Cek apakah ada data
    
    // Loop untuk membaca data dari ResultSet
    while (rs.next()) {
        Object[] row = new Object[6]; // 6 kolom sesuai tabel
        row[0] = rs.getString("id_sewa");
        row[1] = rs.getString("nama_penyewa");
        row[2] = rs.getDate("tanggal");
        row[3] = rs.getString("nomor_kamar");
        row[4] = rs.getString("bulan_setelah"); // Menampilkan bulan setelahnya dengan tahun
        row[5] = rs.getBigDecimal("harga_sewa");
        model.addRow(row);
        adaData = true; // Set true jika ada data
    }

    // Set model ke JTable
    TABELTAMPIL.setModel(model);

    if (!adaData) {
        JOptionPane.showMessageDialog(rootPane, "Tidak ada data yang ditemukan.");
    } else {
        System.out.println("Data berhasil dimuat.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + e.getMessage());
}

    }

  private void bersihForm() {
    TSEWA.setText("");
    TIDPENYEWA.setText("");
    jDateChooser1.setDate(null); // Reset tanggal
    TIDKAMAR.setText("");
    TBULAN.setText("");
    THARGA.setText("");
}
  
    
    private void loadData() {
       PreparedStatement pstmt = null;
     ResultSet rs = null;

     try {
         // Pastikan koneksi sudah diinisialisasi
         if (con == null) {
             KoneksiDB koneksiDB = new KoneksiDB();
             koneksiDB.koneksikoskosan();
             con = koneksiDB.con;
         }

         // Query untuk mengambil data berdasarkan username dari session
         String sql = "SELECT * FROM akun WHERE username = ?";
         pstmt = con.prepareStatement(sql);
         pstmt.setString(1, login.Session.getUsername()); // Gunakan username dari session
         rs = pstmt.executeQuery();

         if (rs.next()) {
             // Set data ke TextField
             username.setText(rs.getString("username"));
             level.setText(rs.getString("level"));

             // Set ikon foto ke JLabel
             String fotoPath = rs.getString("foto"); 
                 if (fotoPath != null && !fotoPath.trim().isEmpty()) {
                     ImageIcon icon = new ImageIcon(fotoPath);
                     java.awt.Image img = icon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); // Dimensi tetap
                     foto.setIcon(new ImageIcon(img));
                 } else {
                     foto.setIcon(null);
                 }

         } else {
             // Menampilkan pesan bahwa pengguna harus login
             JOptionPane.showMessageDialog(this, "Silakan keluar dan login akun Anda!");
             login pindah = new login();
             pindah.setVisible(true);
             this.dispose();  
         }
//        
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
     } finally {
         try {
             if (rs != null) rs.close();
             if (pstmt != null) pstmt.close();
         } catch (Exception e) {
             e.printStackTrace();
         }
     }
//      
    }

    
}
