/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.PreparedStatement;
import Koneksi.KoneksiDB;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oc
 */
public class Dashboard extends javax.swing.JFrame {
    public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql, tgl="";
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    setLocationRelativeTo(null);

    // Inisialisasi koneksi database
    KoneksiDB db = new KoneksiDB();
    db.koneksikoskosan();

    // Ambil koneksi dan statement dari KoneksiDB
    con = db.con;
    stat = db.stat;

    // Validasi apakah koneksi berhasil
    if (stat == null) {
        JOptionPane.showMessageDialog(this, "Koneksi database gagal. Tidak dapat melanjutkan!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Panggil metode untuk menampilkan jumlah kamar
    tampilkanJumlahKamar();
    tampilkanjumlahuser ();
    tampilkanJumlahPenyewa();
    tampilharitanggal();
//    tampilDataSewasemua();
//    tampilDatahutangsemua();
//    tampilTotalHargaSewaHariIni();
//    tampilTotalhutangHariIni();
    loadData();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        kamarkosong = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        penyewa = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        totaluser = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        pengguna = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        datakamar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbayar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbsewa = new javax.swing.JTable();
        hargasewa = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tanggal2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tanggal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        haritanggal = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        hutang = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        haritanggal2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 678));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RGT ");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA USER");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PENYEWA");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TRANSAKSI");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BAYAR BULANAN");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SEWA KAMAR");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LAPORAN");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PEMBUKUAN");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BUKTI BAYAR");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/keluar.png"))); // NOI18N
        jLabel21.setText("KELUAR");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 30));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home2.png"))); // NOI18N
        jLabel38.setText("DASHBOARD");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 60));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 40));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 40));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("DATA KAMAR");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 680));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Kamar Kosong");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        kamarkosong.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        kamarkosong.setForeground(new java.awt.Color(255, 255, 255));
        kamarkosong.setText("0");
        jPanel3.add(kamarkosong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tidur.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 170, 80));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Penyewa");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        penyewa.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        penyewa.setForeground(new java.awt.Color(255, 255, 255));
        penyewa.setText("0");
        jPanel4.add(penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/orang.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 170, 80));

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total User");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        totaluser.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        totaluser.setForeground(new java.awt.Color(255, 255, 255));
        totaluser.setText("0");
        jPanel5.add(totaluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user2.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 170, 80));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESIDENCE GARDEN TOWER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        username.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 50, 50));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setText("DASHBOARD");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        level.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("level");
        level.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelMouseClicked(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 90, -1));

        pengguna.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        pengguna.setForeground(new java.awt.Color(255, 255, 255));
        pengguna.setText("USERNAME :");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jPanel1.add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        role.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("LEVEL :");
        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 780, 70));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Kamar");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        datakamar.setBackground(new java.awt.Color(255, 255, 255));
        datakamar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        datakamar.setForeground(new java.awt.Color(255, 255, 255));
        datakamar.setText("0");
        datakamar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                datakamarInputMethodTextChanged(evt);
            }
        });
        jPanel6.add(datakamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 130, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tidur.png"))); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 170, 80));

        tbbayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor", "Penyewa", "Kamar", "Tanggal", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tbbayar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 360, 210));

        tbsewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor", "Penyewa", "Kamar", "Tanggal"
            }
        ));
        tbsewa.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tbsewa);
        if (tbsewa.getColumnModel().getColumnCount() > 0) {
            tbsewa.getColumnModel().getColumn(0).setResizable(false);
            tbsewa.getColumnModel().getColumn(0).setHeaderValue("Nomor");
            tbsewa.getColumnModel().getColumn(1).setHeaderValue("Penyewa");
            tbsewa.getColumnModel().getColumn(2).setHeaderValue("Kamar");
            tbsewa.getColumnModel().getColumn(3).setHeaderValue("Tanggal");
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 360, 210));

        hargasewa.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        hargasewa.setText("Rp.0");
        getContentPane().add(hargasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggal2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        tanggal2.setForeground(new java.awt.Color(0, 0, 153));
        tanggal2.setText(" ");
        jPanel7.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 40, 210, -1));

        jLabel27.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 153));
        jLabel27.setText("Total Penyewa Telat Bayar");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 360, 290));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggal.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(0, 0, 153));
        tanggal.setText(" ");
        jPanel8.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jLabel31.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 153));
        jLabel31.setText("Transaksi Penyewaan Kamar");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 153));
        jLabel28.setText("Transaksi Pembayaran Kamar");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 360, 290));

        jLabel29.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel29.setText("Pendapatan Sewa ( Hari Ini )");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 250, 20));

        jLabel30.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 255));
        jLabel30.setText("Lihat Detail");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 100, 20));

        haritanggal.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        haritanggal.setText("Hari, Tanggal");
        getContentPane().add(haritanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 210, 20));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dollar.png"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, 100));

        hutang.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        hutang.setText("Rp.0");
        getContentPane().add(hutang, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 120, 20));

        jLabel33.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel33.setText("Hutang Penyewa ( Hari Ini )");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 250, 20));

        jLabel34.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 255));
        jLabel34.setText("Lihat Detail");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 100, 20));

        haritanggal2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        haritanggal2.setText("Hari, Tanggal");
        getContentPane().add(haritanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 210, 20));

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo3.png"))); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 80, 100));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 360, 120));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 360, 120));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("DASHBOARD");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        setSize(new java.awt.Dimension(946, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Dashboard pindah = new Dashboard();
                pindah.setVisible(true);
                this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameMouseClicked

    private void datakamarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_datakamarInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_datakamarInputMethodTextChanged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        datauser pindah = new datauser();
        pindah.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        datapenyewa pindah = new datapenyewa();
        pindah.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        bayarbulanan pindah = new bayarbulanan();
        pindah.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        sewakamar pindah = new sewakamar();
        pindah.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        pembukuan pindah = new pembukuan();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        buktibayar pindah = new buktibayar();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // Membuat instance dari FrameB
        login pindah = new login();

        // Menampilkan pesan konfirmasi
        JOptionPane.showMessageDialog(null, "Anda yakin untuk keluar.");

        // Menutup jendela
        dispose();

        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // Membuat instance dari FrameB
        Dashboard pindah = new Dashboard();
        // Menutup jendela
        dispose();
        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        datakamar pindah = new datakamar();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void levelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_levelMouseClicked

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaMouseClicked

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roleMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        tampilDataSewa();    
        tampiltanggalsewa();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        tampiltanggaltransaksi();
        tampilDatahutanghariini();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datakamar;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel hargasewa;
    private javax.swing.JLabel haritanggal;
    private javax.swing.JLabel haritanggal2;
    private javax.swing.JLabel hutang;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kamarkosong;
    private javax.swing.JLabel level;
    private javax.swing.JLabel pengguna;
    private javax.swing.JLabel penyewa;
    private javax.swing.JLabel role;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel tanggal2;
    private javax.swing.JTable tbbayar;
    private javax.swing.JTable tbsewa;
    private javax.swing.JLabel totaluser;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

   private void tampilkanJumlahKamar() {
    if (stat == null) {
        JOptionPane.showMessageDialog(this, "Koneksi database belum berhasil. Tidak dapat menampilkan jumlah kamar.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Query untuk menghitung jumlah total kamar
        String queryTotal = "SELECT COUNT(*) AS total FROM tbkamar";
        rs = stat.executeQuery(queryTotal); // Eksekusi query total kamar
        if (rs.next()) {
            int totalData = rs.getInt("total"); // Ambil hasil perhitungan total kamar
            datakamar.setText("" + totalData); // Tampilkan di label jumlah kamar
        }

        // Query untuk menghitung jumlah kamar kosong
        String queryKosong = "SELECT COUNT(*) AS totalKosong FROM tbkamar WHERE status = 'tersedia'";
        rs = stat.executeQuery(queryKosong); // Eksekusi query kamar kosong
        if (rs.next()) {
            int totalKosong = rs.getInt("totalKosong"); // Ambil hasil perhitungan kamar kosong
            kamarkosong.setText("" + totalKosong); // Tampilkan di label kamar kosong
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        datakamar.setText("Error menampilkan jumlah data");
        kamarkosong.setText("Error menampilkan kamar kosong");
    }
}


    private void tampilkanJumlahPenyewa() {
       if (stat == null) {
        JOptionPane.showMessageDialog(this, "Koneksi database belum berhasil. Tidak dapat menampilkan jumlah kamar.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Query untuk menghitung jumlah data
        String query = "SELECT COUNT(*) AS total FROM tbpenyewa";
        rs = stat.executeQuery(query); // Eksekusi query

        if (rs.next()) {
            int totalData = rs.getInt("total"); // Ambil hasil perhitungan
           penyewa.setText(""+ totalData); // Tampilkan di label
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        penyewa.setText("Error menampilkan jumlah data");
    }
    
    }
    private void tampilharitanggal() {
    // Format untuk hari dan tanggal
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy");
    Date date = new Date(); // Tanggal hari ini
    String hariTanggal = sdf.format(date); // Format menjadi string

    // Set text pada JLabel
    haritanggal.setText(hariTanggal);
    haritanggal2.setText(hariTanggal);   
}
    private void tampilTotalHargaSewaHariIni() {
   try {
    // Pastikan koneksi database valid
    if (con == null || con.isClosed()) {
        JOptionPane.showMessageDialog(rootPane, "Koneksi database tidak valid.");
        return;
    }

    // Query untuk menjumlahkan harga dari tbbulanan berdasarkan created_at hari ini
    String sql = "SELECT SUM(harga) AS total_harga_sewa " +
                 "FROM tbbulanan " +
                 "WHERE DATE(created_at) = CURDATE()"; // Ambil data hanya untuk hari ini

    // Siapkan PreparedStatement
    PreparedStatement pstmt = con.prepareStatement(sql);
    
    // Cetak query untuk debugging
    System.out.println("Query: " + sql);
    
    // Eksekusi query
    ResultSet rs = pstmt.executeQuery();

    // Jika data ditemukan, tampilkan total harga sewa pada JLabel
    if (rs.next()) {
        BigDecimal totalHargaSewa = rs.getBigDecimal("total_harga_sewa");
        if (totalHargaSewa != null) {
            hargasewa.setText("Rp " + totalHargaSewa.toPlainString());
        } else {
            hargasewa.setText("Rp. 0");
        }
    } else {
        hargasewa.setText("Rp. 0");
        System.out.println("Tidak ada data transaksi hari ini."); // Debugging
    }

    // Tampilkan log jika perlu (opsional)
    System.out.println("Total harga sewa dari tbbulanan hari ini berhasil dimuat.");

} catch (Exception e) {
    // Tangani kesalahan SQL
    JOptionPane.showMessageDialog(rootPane, "Gagal memuat total harga sewa: " + e.getMessage());
    e.printStackTrace(); // Cetak stack trace untuk debugging
}

}
    private void tampiltanggalsewa() {
    // Format untuk hanya menampilkan tanggal, bulan, dan tahun
    SimpleDateFormat sdf = new SimpleDateFormat("dd MM yyyy");
    Date date = new Date(); // Tanggal hari ini
    String tanggal = sdf.format(date); // Format menjadi string

    // Set text pada JLabel untuk menampilkan tanggal dengan tambahan "TANGGAL : "
    this.tanggal.setText("TANGGAL : " + tanggal);
}
    
     private void tampiltanggaltransaksi() {
    // Format untuk hanya menampilkan tanggal, bulan, dan tahun
    SimpleDateFormat sdf = new SimpleDateFormat("dd MM yyyy");
    Date date = new Date(); // Tanggal hari ini
    String tanggal = sdf.format(date); // Format menjadi string

    // Set text pada JLabel untuk menampilkan tanggal dengan tambahan "TANGGAL : "
    this.tanggal2.setText("TANGGAL : " + tanggal);
}
    
     private void loadData() {
     PreparedStatement pstmt = null;
     ResultSet rs = null;

     try {
         // Pastikan koneksi sudah diinisialisasi
         if (con == null) {
             KoneksiDB koneksiDB = new KoneksiDB();
             koneksiDB.koneksikoskosan();
             con = koneksiDB.con;
         }

         // Query untuk mengambil data berdasarkan username dari session
         String sql = "SELECT * FROM akun WHERE username = ?";
         pstmt = con.prepareStatement(sql);
         pstmt.setString(1, login.Session.getUsername()); // Gunakan username dari session
         rs = pstmt.executeQuery();

         if (rs.next()) {
             // Set data ke TextField
             username.setText(rs.getString("username"));
             level.setText(rs.getString("level"));

             // Set ikon foto ke JLabel
             String fotoPath = rs.getString("foto"); 
                 if (fotoPath != null && !fotoPath.trim().isEmpty()) {
                     ImageIcon icon = new ImageIcon(fotoPath);
                     java.awt.Image img = icon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); // Dimensi tetap
                     foto.setIcon(new ImageIcon(img));
                 } else {
                     foto.setIcon(null);
                 }

         } else {
             // Menampilkan pesan bahwa pengguna harus login
             JOptionPane.showMessageDialog(this, "Silakan keluar dan login akun Anda!");
             login pindah = new login();
             pindah.setVisible(true);
             this.dispose();  
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
     } finally {
         try {
             if (rs != null) rs.close();
             if (pstmt != null) pstmt.close();
         } catch (Exception e) {
             e.printStackTrace();
         }
     }
     }
   private void tampilDataSewa() {
 try {
    // Query untuk mengambil data dari tbbulanan berdasarkan created_at hari ini
    String sql = "SELECT idsewa, nama_penyewa, tanggalsewa, nokamar, bulan, harga, created_at " +
                 "FROM tbbulanan " +
                 "WHERE DATE(created_at) = CURDATE()";

    // Siapkan Statement
    Statement stmt = con.createStatement();
    
    // Eksekusi query
    ResultSet rs = stmt.executeQuery(sql);

    // Buat model untuk JTable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Sewa");
    model.addColumn("Nama Penyewa");
    model.addColumn("Tanggal Sewa");
    model.addColumn("Nomor Kamar");
    model.addColumn("Harga Sewa");

    // Loop untuk membaca data dari ResultSet
    while (rs.next()) {
        Object[] row = new Object[7];
        row[0] = rs.getString("idsewa");
        row[1] = rs.getString("nama_penyewa");
        row[2] = rs.getDate("tanggalsewa");
        row[3] = rs.getString("nokamar");
        row[4] = rs.getBigDecimal("harga");
        model.addRow(row);
    }

    // Set model ke JTable
    tbsewa.setModel(model);

    // Log hasil
    System.out.println("Data sewa yang dibuat hari ini berhasil dimuat.");

} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + e.getMessage());
}

}
     
     private void tampilDataSewasemua() {
  try {
    // Query untuk mengambil data dari tbbulanan berdasarkan created_at hari ini
    String sql = "SELECT idsewa, nama_penyewa, tanggalsewa, nokamar, bulan, harga, created_at " +
                 "FROM tbbulanan " ;
               

    // Siapkan Statement
    Statement stmt = con.createStatement();
    
    // Eksekusi query
    ResultSet rs = stmt.executeQuery(sql);

    // Buat model untuk JTable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Sewa");
    model.addColumn("Nama Penyewa");
    model.addColumn("Tanggal Sewa");
    model.addColumn("Nomor Kamar");

    // Loop untuk membaca data dari ResultSet
    while (rs.next()) {
        Object[] row = new Object[7];
        row[0] = rs.getString("idsewa");
        row[1] = rs.getString("nama_penyewa");
        row[2] = rs.getDate("tanggalsewa");
        row[3] = rs.getString("nokamar");
     
      
        model.addRow(row);
    }

    // Set model ke JTable
    tbsewa.setModel(model);

    // Log hasil
    System.out.println("Data sewa yang dibuat hari ini berhasil dimuat.");

} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + e.getMessage());
}

}
     
     
    private void tampilkanjumlahuser() {
        if (stat == null) {
        JOptionPane.showMessageDialog(this, "Koneksi database belum berhasil. Tidak dapat menampilkan jumlah kamar.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Query untuk menghitung jumlah data
        String query = "SELECT COUNT(*) AS total FROM akun";
        rs = stat.executeQuery(query); // Eksekusi query

        if (rs.next()) {
            int totalData = rs.getInt("total"); // Ambil hasil perhitungan
            totaluser.setText(""+ totalData); // Tampilkan di label
           
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        totaluser.setText("Error menampilkan jumlah data");
    }
    }

    private void tampilDatahutangsemua() {
      
    try {
        // Query untuk mengambil data dari tbbulanan yang sudah telat lebih dari sebulan
        String sql = "SELECT idsewa, nama_penyewa, tanggalsewa, nokamar, bulan, harga, created_at " +
                     "FROM tbbulanan " +
                     "WHERE tanggalsewa <= DATE_SUB(CURDATE(), INTERVAL 1 MONTH)"; // Ambil data lebih dari 30 hari lalu

        // Siapkan Statement
        Statement stmt = con.createStatement();
        
        // Eksekusi query
        ResultSet rs = stmt.executeQuery(sql);

        // Buat model untuk JTable
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Sewa");
        model.addColumn("Nama Penyewa");
        model.addColumn("Tanggal Sewa");
        model.addColumn("Nomor Kamar");
    

        // Loop untuk membaca data dari ResultSet
        while (rs.next()) {
            Object[] row = new Object[7];
            row[0] = rs.getString("idsewa");
            row[1] = rs.getString("nama_penyewa");
            row[2] = rs.getDate("tanggalsewa");
            row[3] = rs.getString("nokamar");
            model.addRow(row);
        }

        // Set model ke JTable
        tbbayar.setModel(model);

        // Log hasil
        System.out.println("Data hutang (telat lebih dari sebulan) berhasil dimuat.");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + e.getMessage());
    }
}

    private void tampilDatahutanghariini() {
     try {
    // Query untuk mengambil data dari tbbulanan yang sudah telat lebih dari sebulan 
    // tetapi baru dibuat (created_at) hari ini
    String sql = "SELECT idsewa, nama_penyewa, tanggalsewa, nokamar, bulan, harga, created_at " +
                 "FROM tbbulanan " +
                 "WHERE tanggalsewa <= DATE_SUB(CURDATE(), INTERVAL 1 MONTH) ";  // Telat lebih dari sebulan
                

    // Siapkan Statement
    Statement stmt = con.createStatement();
    
    // Eksekusi query
    ResultSet rs = stmt.executeQuery(sql);

    // Buat model untuk JTable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Sewa");
    model.addColumn("Nama Penyewa");
    model.addColumn("Tanggal Sewa");
    model.addColumn("Nomor Kamar");
    model.addColumn("Harga Sewa");

    // Loop untuk membaca data dari ResultSet
    while (rs.next()) {
        Object[] row = new Object[7];
        row[0] = rs.getString("idsewa");
        row[1] = rs.getString("nama_penyewa");
        row[2] = rs.getDate("tanggalsewa");
        row[3] = rs.getString("nokamar");
        row[4] = rs.getBigDecimal("harga");
        model.addRow(row);
    }

    // Set model ke JTable
    tbbayar.setModel(model);

    // Log hasil
    System.out.println("Data hutang (telat lebih dari sebulan dan dibuat hari ini) berhasil dimuat.");

} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + e.getMessage());
}

    }

    private void tampilTotalhutangHariIni() {
     
    try {
    // Query untuk menjumlahkan harga dari tbbulanan yang memiliki tanggalsewa lebih dari sebulan lalu
    // dan hanya data yang dibuat hari ini (created_at hari ini)
    String sql = "SELECT SUM(harga) AS total_hutang " +
                 "FROM tbbulanan " +
                 "WHERE tanggalsewa <= DATE_SUB(CURDATE(), INTERVAL 1 MONTH) "; // Data yang telat lebih dari sebulan
                 
    
    // Siapkan PreparedStatement
    PreparedStatement pstmt = con.prepareStatement(sql);
    
    // Eksekusi query
    ResultSet rs = pstmt.executeQuery();

    // Jika data ditemukan, tampilkan total hutang
    if (rs.next()) {
        BigDecimal totalHutang = rs.getBigDecimal("total_hutang");
        if (totalHutang != null) {
            hutang.setText("Rp " + totalHutang.toPlainString());
        } else {
            hutang.setText("Rp 0");
        }
    } else {
        hutang.setText("Rp 0");
    }

    // Log hasil
    System.out.println("Total hutang hari ini berhasil dimuat.");

} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Gagal memuat total hutang: " + e.getMessage());
    e.printStackTrace(); // Debugging jika ada error
}

}

}
