/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.PreparedStatement;
import Koneksi.KoneksiDB;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author oc
 */
public class datapenyewa extends javax.swing.JFrame {
     public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql, tgl="";
    /**
     * Creates new form datapenyewa
     */
    public datapenyewa() {
       initComponents();
//        this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        KoneksiDB db = new KoneksiDB();
        db.koneksikoskosan();
        con=db.con;
        stat=db.stat;
        rs=db.rs;
        
        TIDPENYEWA.setEnabled(false);
        
        tampildatapenyewa();
        loadData ();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        pengguna = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenyewa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TPEKERJAAN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TALAMATASAL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TNOMOR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TEMAIL = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tpencarian = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TIDPENYEWA = new javax.swing.JTextField();
        TNAMA = new javax.swing.JTextField();
        TNOMORIDENTITAS = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        CJENISKELAMIN = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnfoto = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        ttampil = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA USER");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PENYEWA");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TRANSAKSI");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BAYAR BULANAN");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SEWA KAMAR");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RGT ");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home2.png"))); // NOI18N
        jLabel38.setText("DASHBOARD");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 40));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 60));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 40));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("DATA KAMAR");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LAPORAN");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BUKTI BAYAR");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PEMBUKUAN");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 40));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/keluar.png"))); // NOI18N
        jLabel21.setText("KELUAR");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 710));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 50, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESIDENCE GARDEN TOWER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        username.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));

        level.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("level");
        level.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelMouseClicked(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, -1));

        pengguna.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        pengguna.setForeground(new java.awt.Color(255, 255, 255));
        pengguna.setText("USERNAME :");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jPanel1.add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        role.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("LEVEL :");
        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 810, 70));

        tabelPenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPenyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPenyewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPenyewa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 780, 180));

        jLabel6.setText("ID Penyewa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 200, 20));

        jLabel7.setText("Nama Penyewa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, 20));

        jLabel8.setText("Nomor Identitas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, 20));

        jLabel9.setText("Tanggal Lahir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 200, 20));

        TPEKERJAAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPEKERJAANActionPerformed(evt);
            }
        });
        getContentPane().add(TPEKERJAAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 250, 30));

        jLabel10.setText("Pekerjaan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 190, 20));

        TALAMATASAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TALAMATASALActionPerformed(evt);
            }
        });
        getContentPane().add(TALAMATASAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 250, 30));

        jLabel11.setText("Alamat Asal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 190, 20));

        TNOMOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNOMORActionPerformed(evt);
            }
        });
        getContentPane().add(TNOMOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 250, 30));

        jLabel12.setText("Nomor Telepon");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 190, 20));

        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 190, 20));

        TEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEMAILActionPerformed(evt);
            }
        });
        getContentPane().add(TEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 250, 30));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 40));

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CENCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 90, 40));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 90, 40));

        jLabel14.setText("Jenis Kelamin");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 200, 20));

        jButton4.setBackground(new java.awt.Color(0, 204, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 90, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, 40));
        getContentPane().add(tpencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 160, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TIDPENYEWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDPENYEWAActionPerformed(evt);
            }
        });

        TNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNAMAActionPerformed(evt);
            }
        });

        TNOMORIDENTITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNOMORIDENTITASActionPerformed(evt);
            }
        });

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        CJENISKELAMIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "PRIA", "WANITA" }));

        jLabel2.setText("Foto");

        btnfoto.setText("File");
        btnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TIDPENYEWA, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TNOMORIDENTITAS, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(403, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CJENISKELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnfoto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ttampil))
                        .addGap(18, 18, 18)
                        .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TIDPENYEWA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TNOMORIDENTITAS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CJENISKELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnfoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttampil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 780, 280));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 780, 240));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setText("DATA PENYEWA");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TIDPENYEWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDPENYEWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDPENYEWAActionPerformed

    private void TNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNAMAActionPerformed

    private void TNOMORIDENTITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNOMORIDENTITASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNOMORIDENTITASActionPerformed

    private void TPEKERJAANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPEKERJAANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPEKERJAANActionPerformed

    private void TALAMATASALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TALAMATASALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TALAMATASALActionPerformed

    private void TNOMORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNOMORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNOMORActionPerformed

    private void TEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEMAILActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
// Menambahkan data baru ke database
try {
    String sql = "INSERT INTO tbpenyewa (id_penyewa, nama_penyewa, nomor_identitas, tanggal_lahir, jenis_kelamin, pekerjaan, alamat_asal, nomor_telepon, email, foto) " +
                 "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1, TIDPENYEWA.getText());
    ps.setString(2, TNAMA.getText());
    ps.setString(3, TNOMORIDENTITAS.getText());
    ps.setString(4, new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate()));
    ps.setString(5, CJENISKELAMIN.getSelectedItem().toString());
    ps.setString(6, TPEKERJAAN.getText());
    ps.setString(7, TALAMATASAL.getText());
    ps.setString(8, TNOMOR.getText());
    ps.setString(9, TEMAIL.getText());
    ps.setString(10, ttampil.getText());
    
    ps.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data telah disimpan");

    // Membersihkan form setelah menyimpan
    bersih();
    // Memperbarui tampilan data
    tampildatapenyewa();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bersih(); 
        tampildatapenyewa();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int row = tabelPenyewa.getSelectedRow();
if (row != -1) {
    String tanggalLahir;
    
    // Pastikan tanggal tidak null
    if (jDateChooser1.getDate() != null) {
        tanggalLahir = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate());
    } else {
        JOptionPane.showMessageDialog(rootPane, "Tanggal lahir tidak boleh kosong");
        return;
    }

    String idPenyewa = tabelPenyewa.getValueAt(row, 0).toString(); // Ambil id_penyewa dari tabel

    try {
        String sql = "UPDATE tbpenyewa SET nama_penyewa = ?, nomor_identitas = ?, tanggal_lahir = ?, " +
                     "jenis_kelamin = ?, pekerjaan = ?, alamat_asal = ?, nomor_telepon = ?, email = ?, foto = ? " +
                     "WHERE id_penyewa = ?";

        PreparedStatement ps = con.prepareStatement(sql);

        // Mengatur parameter
        ps.setString(1, TNAMA.getText());
        ps.setString(2, TNOMORIDENTITAS.getText());
        ps.setString(3, tanggalLahir);
        ps.setString(4, CJENISKELAMIN.getSelectedItem().toString());
        ps.setString(5, TPEKERJAAN.getText());
        ps.setString(6, TALAMATASAL.getText());
        ps.setString(7, TNOMOR.getText());
        ps.setString(8, TEMAIL.getText());
        ps.setString(9, ttampil.getText());
        ps.setString(10, idPenyewa);

        // Eksekusi query
        ps.executeUpdate();

        JOptionPane.showMessageDialog(rootPane, "Data berhasil diupdate");

        // Refresh data tabel
        tampildatapenyewa();
        bersih();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Data gagal diupdate: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(rootPane, "Pilih baris yang akan diupdate");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
    int row = tabelPenyewa.getSelectedRow();

    // Pastikan baris yang dipilih valid
    if (row != -1) {
        String idPenyewa = tabelPenyewa.getValueAt(row, 0 ).toString(); // Ambil id_penyewa dari tabel
        
        try {
            String sql = "DELETE FROM tbpenyewa WHERE id_penyewa = '" + idPenyewa + "'";
            Statement stat = con.createStatement();
            stat.execute(sql);

            JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus");

            // Refresh data tabel
            tampildatapenyewa();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data gagal dihapus: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Pilih baris yang akan dihapus");
    }
    bersih();
    tampildatapenyewa();
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        
        if (jDateChooser1.getDate() != null) {
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(pattern);
        tgl = format.format(jDateChooser1.getDate());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void tabelPenyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenyewaMouseClicked
    
    // Mendapatkan baris yang dipilih
int row = tabelPenyewa.getSelectedRow();

// Pastikan baris yang dipilih valid
if (row != -1) {
    // Mengambil data dari baris yang dipilih
    String idPenyewa = tabelPenyewa.getValueAt(row, 0).toString();
    String namaPenyewa = tabelPenyewa.getValueAt(row, 1).toString();
    String nomorIdentitas = tabelPenyewa.getValueAt(row, 2).toString();
    String tanggalLahirString = tabelPenyewa.getValueAt(row, 3).toString();
    String jenisKelamin = tabelPenyewa.getValueAt(row, 4).toString();
    String pekerjaan = tabelPenyewa.getValueAt(row, 5).toString();
    String alamatAsal = tabelPenyewa.getValueAt(row, 6).toString();
    String nomorTelepon = tabelPenyewa.getValueAt(row, 7).toString();
    String email = tabelPenyewa.getValueAt(row, 8).toString();
    String foto = tabelPenyewa.getValueAt(row, 9).toString();

    // Konversi String tanggal menjadi Date
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); // Sesuaikan dengan format yang digunakan
    Date tanggalLahir = null;
    try {
        tanggalLahir = format.parse(tanggalLahirString);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(null, "Format tanggal tidak valid: " + e.getMessage()); // Tangani pengecualian jika format tidak valid
        return;
    }

    // Mengisi form dengan data yang diambil
    TIDPENYEWA.setText(idPenyewa);
    TNAMA.setText(namaPenyewa);
    TNOMORIDENTITAS.setText(nomorIdentitas);
    jDateChooser1.setDate(tanggalLahir); 
    CJENISKELAMIN.setSelectedItem(jenisKelamin);
    TPEKERJAAN.setText(pekerjaan);
    TALAMATASAL.setText(alamatAsal);
    TNOMOR.setText(nomorTelepon);
    TEMAIL.setText(email);
    ttampil.setText(foto);

    // Menampilkan file path di ttampil (gunakan path relatif)
    if (foto != null && !foto.isEmpty()) {
        ttampil.setText(foto); // Mengisi path gambar atau nama file ke dalam JTextField ttampil
    }

    // Mengatur gambar pada label jika ada
    if (foto != null && !foto.isEmpty()) {
        // Jika foto ada, tampilkan gambar pada JLabel
        File fotoFile = new File(foto); // Membuat objek File untuk path foto
        if (fotoFile.exists()) {
            ImageIcon imageIcon = new ImageIcon(fotoFile.getAbsolutePath()); // Pastikan 'foto' adalah path gambar yang valid
            Image scaledImage = imageIcon.getImage().getScaledInstance(lblfoto.getWidth(), lblfoto.getHeight(), Image.SCALE_SMOOTH);
            lblfoto.setIcon(new ImageIcon(scaledImage)); // Menampilkan gambar pada label
        } else {
            lblfoto.setIcon(null); // Jika file tidak ada, hilangkan gambar
            JOptionPane.showMessageDialog(null, "File gambar tidak ditemukan: " + foto);
        }
    } else {
        // Jika tidak ada foto, hilangkan gambar
        lblfoto.setIcon(null);
    }
} else {
    JOptionPane.showMessageDialog(null, "Pilih baris yang akan diambil datanya.");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_tabelPenyewaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String id_penyewa = tpencarian.getText().trim(); // Mengambil input dari JTextField

        if (id_penyewa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan ID Buku untuk mencari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String sql = "SELECT * FROM tbpenyewa WHERE id_penyewa = '" + id_penyewa + "'";
            Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery(sql);

            DefaultTableModel tabel = new DefaultTableModel();
                tabel.addColumn("ID");
                tabel.addColumn("ID Penyewa");
                tabel.addColumn("Nama Penyewa");
                tabel.addColumn("Nomor Identitas");
                tabel.addColumn("Tanggal Lahir");
                tabel.addColumn("Jenis Kelamin");
                tabel.addColumn("Pekerjaan");
                tabel.addColumn("Alamat Asal");
                tabel.addColumn("Nomor Telepon");
                tabel.addColumn("Email");

            if (res.next()) {
                // Menambahkan data hasil pencarian ke tabel
                tabel.addRow(new Object[]{
                    res.getInt("id"),
                    res.getString("id_penyewa"),
                    res.getString("nama_penyewa"),
                    res.getString("nomor_identitas"),
                    res.getDate("tanggal_lahir"),
                    res.getString("jenis_kelamin"),
                    res.getString("pekerjaan"),
                    res.getString("alamat_asal"),
                    res.getString("nomor_telepon"),
                    res.getString("email")
                });
                 tabelPenyewa.setModel(tabel); // Menampilkan hasil pencarian di JTable
                 JOptionPane.showMessageDialog(rootPane, "ini data penyewa dengan ID " +  tpencarian.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Penyewa dengan ID " + id_penyewa + " tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampildatapenyewa(); // Menampilkan semua data jika tidak ada hasil
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        Dashboard pindah = new Dashboard();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void btnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfotoActionPerformed
        // Membuat JFileChooser
JFileChooser fileChooser = new JFileChooser();
fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

// Filter file gambar
fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
        "Gambar (JPG, PNG, GIF)", "jpg", "png", "gif"));

// Menampilkan JFileChooser
int result = fileChooser.showOpenDialog(this);

if (result == JFileChooser.APPROVE_OPTION) {
    // Mendapatkan file yang dipilih
    File selectedFile = fileChooser.getSelectedFile();
    String filePath = selectedFile.getAbsolutePath();
    String fileName = selectedFile.getName();  // Hanya mengambil nama file

   

    // Menampilkan nama file di JTextField (misalnya jika hanya nama file yang diperlukan)
    // Jika Anda hanya ingin nama file tanpa path, gunakan fileName
    ttampil.setText(filePath);  // Menampilkan hanya nama file di JTextField

    // Menampilkan gambar di JLabel
    ImageIcon imageIcon = new ImageIcon(filePath);
    Image scaledImage = imageIcon.getImage().getScaledInstance(lblfoto.getWidth(), lblfoto.getHeight(), Image.SCALE_SMOOTH);
    lblfoto.setIcon(new ImageIcon(scaledImage));
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfotoActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        datauser pindah = new datauser();
        pindah.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        datapenyewa pindah = new datapenyewa();
        pindah.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        bayarbulanan pindah = new bayarbulanan();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
         sewakamar pindah = new sewakamar();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // Membuat instance dari FrameB
        Dashboard pindah = new Dashboard();
        // Menutup jendela
        dispose();
        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        datakamar pindah = new datakamar();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44MouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameMouseClicked

    private void levelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_levelMouseClicked

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaMouseClicked

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roleMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        buktibayar pindah = new buktibayar();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        pembukuan pindah = new pembukuan();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // Membuat instance dari FrameB
        login pindah = new login();

        // Menampilkan pesan konfirmasi
        JOptionPane.showMessageDialog(null, "Anda yakin untuk keluar.");

        // Menutup jendela
        dispose();

        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapenyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CJENISKELAMIN;
    private javax.swing.JTextField TALAMATASAL;
    private javax.swing.JTextField TEMAIL;
    private javax.swing.JTextField TIDPENYEWA;
    private javax.swing.JTextField TNAMA;
    private javax.swing.JTextField TNOMOR;
    private javax.swing.JTextField TNOMORIDENTITAS;
    private javax.swing.JTextField TPEKERJAAN;
    private javax.swing.JButton btnfoto;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JLabel level;
    private javax.swing.JLabel pengguna;
    private javax.swing.JLabel role;
    private javax.swing.JTable tabelPenyewa;
    private javax.swing.JTextField tpencarian;
    private javax.swing.JTextField ttampil;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private void bersih() {
   
    TNAMA.setText("");
    TNOMORIDENTITAS.setText("");
   // Bersihkan tanggal di JDateChooser
    jDateChooser1.setDate(null);
    CJENISKELAMIN.setSelectedIndex(0); // Reset combo box ke pilihan pertama
    TPEKERJAAN.setText("");
    TALAMATASAL.setText("");
    TNOMOR.setText("");
    TEMAIL.setText("");
    ttampil.setText("");
    lblfoto.setIcon(null);
    
    }

    private void tampildatapenyewa() {
    DefaultTableModel model = new DefaultTableModel();
//    model.addColumn("ID");
    model.addColumn("ID Penyewa");
    model.addColumn("Nama Penyewa");
    model.addColumn("Nomor Identitas");
    model.addColumn("Tanggal Lahir");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Pekerjaan");
    model.addColumn("Alamat Asal");
    model.addColumn("Nomor Telepon");
    model.addColumn("Email");
    model.addColumn("Foto");

    try {
        String sql = "SELECT * FROM tbpenyewa";
        Statement stat = con.createStatement();
        ResultSet res = stat.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
//                res.getInt("id"),
                res.getString("id_penyewa"),
                res.getString("nama_penyewa"),
                res.getString("nomor_identitas"),
                res.getDate("tanggal_lahir"),
                res.getString("jenis_kelamin"),
                res.getString("pekerjaan"),
                res.getString("alamat_asal"),
                res.getString("nomor_telepon"),
                res.getString("email"),
                res.getString("foto")
            });
        }

        // Set model ke tabel
        tabelPenyewa.setModel(model);
        
        // Ambil ID buku terakhir
          sql = "SELECT id_penyewa FROM tbpenyewa ORDER BY id_penyewa DESC LIMIT 1";
          rs = stat.executeQuery(sql);
          String idBukuBaru = "KDP001"; // Default jika tabel kosong

          if (rs.next()) {
              String lastId = rs.getString("id_penyewa"); // ID terakhir, misalnya "KDB005"
              int lastNumber = Integer.parseInt(lastId.substring(3)); // Ambil angka setelah "KDB"
              lastNumber++; // Tambahkan 1
              idBukuBaru = String.format("KDP%03d", lastNumber); // Format ulang menjadi "KDB" + 3 digit angka
          }

          // Tampilkan ID buku baru ke TIDBUKU
          TIDPENYEWA.setText(idBukuBaru);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Gagal menampilkan data: " + e.getMessage());
    }
    }

    private void loadData() {
     PreparedStatement pstmt = null;
     ResultSet rs = null;

     try {
         // Query untuk mengambil data berdasarkan username dari session
         String sql = "SELECT * FROM akun WHERE username = ?";
         pstmt = con.prepareStatement(sql);
         pstmt.setString(1, login.Session.getUsername()); // Gunakan username dari session
         rs = pstmt.executeQuery();

         if (rs.next()) {
             // Set data ke TextField
             username.setText(rs.getString("username"));
             level.setText(rs.getString("level"));

             // Set ikon foto ke JLabel
             String fotoPath = rs.getString("foto"); 
                 if (fotoPath != null && !fotoPath.trim().isEmpty()) {
                     ImageIcon icon = new ImageIcon(fotoPath);
                     java.awt.Image img = icon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); // Dimensi tetap
                     foto.setIcon(new ImageIcon(img));
                 } else {
                     foto.setIcon(null);
                 }

         } else {
             // Menampilkan pesan bahwa pengguna harus login
             JOptionPane.showMessageDialog(this, "Silakan keluar dan login akun Anda!");
             login pindah = new login();
             pindah.setVisible(true);
             this.dispose();  
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
     } finally {
         try {
             if (rs != null) rs.close();
             if (pstmt != null) pstmt.close();
         } catch (Exception e) {
             e.printStackTrace();
         }
     }
    }

    
}
