/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.PreparedStatement;
import Koneksi.KoneksiDB;
import form.Dashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

    
/**
 *
 * @author oc
 */
public class login extends javax.swing.JFrame {
    public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql, tgl="";
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        KoneksiDB db = new KoneksiDB();
        db.koneksikoskosan();
        con=db.con;
        stat=db.stat;
        rs=db.rs;
    }

    


    public class Session {
     
        private static String username; // Username pengguna
        private static String level;    // Level pengguna

        public static void setUsername(String username) {
            Session.username = username;
        }

        public static String getUsername() {
            return username;
        }

        public static void setLevel(String level) {
            Session.level = level;
        }

        public static String getLevel() {
            return level;
        }

        public static void clearSession() {
            username = null;
            level = null;
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlevel = new javax.swing.JComboBox<>();
        tpassword = new javax.swing.JPasswordField();
        tusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tlevel.setForeground(new java.awt.Color(255, 153, 0));
        tlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "ADMIN", "KARYAWAN" }));
        tlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlevelActionPerformed(evt);
            }
        });
        getContentPane().add(tlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 320, 50));

        tpassword.setForeground(new java.awt.Color(255, 153, 0));
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 320, 50));

        tusername.setForeground(new java.awt.Color(255, 153, 0));
        tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 320, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 140, 50));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BATAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 160, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aaa (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             String username = tusername.getText(); // Ambil username dari JTextField
        String password = new String(tpassword.getPassword()); // Ambil password dari JPasswordField
        String level = new String((String) tlevel.getSelectedItem());
        // Panggil metode login
        loginn(username, password, level);
// TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
            tusername.setText(""); // Mengosongkan field harga sewa
            tpassword.setText(""); // Mengosongkan field lantai
            tlevel.setSelectedIndex(0); // Mengatur pilihan kapasitas kamar ke index pertama
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlevelActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> tlevel;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
   private void loginn(String username, String password, String level) {
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        // Validasi input kosong
        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!");
            return;
        }
        if (password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!");
            return;
        }
        if ("PILIH".equalsIgnoreCase(level)) {
            JOptionPane.showMessageDialog(null, "Silakan pilih level pengguna!");
            return;
        }

        // Query untuk memeriksa username dan level
        String sql = "SELECT * FROM akun WHERE username = ? AND level = ?";
        pstmt = con.prepareStatement(sql);
        pstmt.setString(1, username);
        pstmt.setString(2, level);
        rs = pstmt.executeQuery();

        if (rs.next()) {
            // Ambil password yang tersimpan di database
            String storedPassword = rs.getString("password");

            // Verifikasi password secara langsung tanpa hash
            if (password.equals(storedPassword)) {
                JOptionPane.showMessageDialog(null, "Login Berhasil!");

                // Set data pengguna ke dalam session
                Session.setUsername(rs.getString("username")); // Simpan username
                Session.setLevel(rs.getString("level")); // Simpan level

                // Buka Dashboard sesuai level
                switch (level.toUpperCase()) {
                    case "ADMIN":
                        new Dashboard().setVisible(true);
                        break;
                    case "KARYAWAN":
                        new Dashboard1().setVisible(true);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Level tidak dikenali!");
                        return;
                }

                this.dispose(); // Tutup jendela login
                return; // Keluar dari method setelah login berhasil
            } else {
                JOptionPane.showMessageDialog(null, "Password salah!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username atau level tidak ditemukan!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Login Gagal: " + e.getMessage());
    } finally {
        // Tutup ResultSet dan PreparedStatement jika sudah tidak digunakan
        try {
            if (rs != null) rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            if (pstmt != null) pstmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
}
