/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.PreparedStatement;
import Koneksi.KoneksiDB;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.TreeSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author oc
 */
public class pembukuan extends javax.swing.JFrame {
     public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql, tgl="", tb="";
    /**
     * Creates new form datapenyewa
     */
    public pembukuan() {
       initComponents();
//        this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        KoneksiDB db = new KoneksiDB();
        db.koneksikoskosan();
        con=db.con;
        stat=db.stat;
        rs=db.rs;
        
       
//        tampilDataSewa();
//        tampildatapenyewa();
        loadData ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        pengguna = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELTAMPIL = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA USER");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PENYEWA");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TRANSAKSI");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BAYAR BULANAN");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SEWA KAMAR");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RGT ");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home2.png"))); // NOI18N
        jLabel38.setText("DASHBOARD");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 40));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 60));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 40));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("DATA KAMAR");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LAPORAN");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BUKTI BAYAR");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PEMBUKUAN");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 40));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/keluar.png"))); // NOI18N
        jLabel21.setText("KELUAR");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 710));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 50, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESIDENCE GARDEN TOWER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        username.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));

        level.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("level");
        level.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelMouseClicked(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, -1));

        pengguna.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        pengguna.setForeground(new java.awt.Color(255, 255, 255));
        pengguna.setText("USERNAME :");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jPanel1.add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        role.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("LEVEL :");
        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 810, 70));

        TABELTAMPIL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABELTAMPIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELTAMPILMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABELTAMPIL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 780, 450));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CETAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 780, 520));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setText("PEMBUKUAN");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StringBuilder dataPeminjam = new StringBuilder();

// Menambahkan Kop Laporan di bagian atas
dataPeminjam.append("                         RESIDENCE GARDEN TOWER\n");
dataPeminjam.append("                   Jl. Soekarnohatta No.1, Pekanbaru, Riau\n");
dataPeminjam.append("                        Telepon: (0761) 123456789\n");
dataPeminjam.append("=================================================================================\n");

// Menambahkan header kolom
dataPeminjam.append(String.format("%-9s %-16s %-14s %-9s %-6s %-6s %-12s\n",
    "ID Sewa", "Nama Penyewa", "No. Kamar", "Bulan", "Harga", "Tanggal Sewa", "Total Bayar"));
dataPeminjam.append("---------------------------------------------------------------------------------\n");

try {
    // Mengambil data dari database
    String sql = "SELECT * FROM tbbulanan";
    Statement stat = con.createStatement();
    ResultSet rs = stat.executeQuery(sql);

    LocalDate today = LocalDate.now(); // Tanggal hari ini

    double totalBayarSemua = 0; // Menyimpan total bayar keseluruhan

    while (rs.next()) {
        // Mengambil data dari database
        String idSewa = rs.getString("idsewa");
        String namaPenyewa = rs.getString("nama_penyewa");
        String noKamar = rs.getString("nokamar");
        String bulan = rs.getString("bulan");
        String harga = rs.getString("harga");
        String tanggalSewa = rs.getDate("tanggalsewa").toString();

        // Menghitung total bayar (misalnya harga * 1 jika hanya mencetak harga)
        double hargaValue = Double.parseDouble(harga);
        totalBayarSemua += hargaValue; // Menambahkan ke total bayar keseluruhan

        // Menambahkan data ke StringBuilder
        dataPeminjam.append(String.format("%-7s %-15s %-14s %-9s %-5s %-6s %-12s\n",
            idSewa, namaPenyewa, noKamar, bulan, harga, tanggalSewa, harga));

        // Memindahkan teks panjang ke baris berikutnya jika kolom terlalu panjang
        if (idSewa.length() > 12) {
            dataPeminjam.append(String.format("%-7s\n", idSewa.substring(12)));
        }
        if (namaPenyewa.length() > 26) {
            dataPeminjam.append(String.format("%-32s %-15s\n", "", namaPenyewa.substring(26)));
        }
        if (noKamar.length() > 7) {
            dataPeminjam.append(String.format("%-33s %-13s\n", "", noKamar.substring(7)));
        }
        if (bulan.length() > 10) {
            dataPeminjam.append(String.format("%-73s %-10s\n", "", bulan.substring(10)));
        }
        if (harga.length() > 13) {
            dataPeminjam.append(String.format("%-93s %-13s\n", "", harga.substring(13)));
        }
        if (tanggalSewa.length() > 12) {
            dataPeminjam.append(String.format("%-105s %-12s\n", "", tanggalSewa.substring(12)));
        }
        if (harga.length() > 12) {
            dataPeminjam.append(String.format("%-117s %-12s\n", "", harga.substring(12)));
        }
    }

    // Menambahkan total bayar setelah semua data
    dataPeminjam.append("                                             Total Bayar Semua: Rp. " + String.format("%,.2f", totalBayarSemua) + "\n");

    dataPeminjam.append("\n");
    dataPeminjam.append("                                                       Pekanbaru, " + java.time.LocalDate.now() + "\n\n");
    dataPeminjam.append("                                                        Pimpinan Residence Garden Tower\n\n\n\n");
    dataPeminjam.append("                                                          -----------------------\n");
    dataPeminjam.append("                                                               (Kelompok 3)\n");

    // Membuat instance dari cetakpeminjam
    cetak formCetakPeminjam = new cetak();
    formCetakPeminjam.setVisible(true);

    // Menampilkan data di JTextArea pada form cetakpeminjam
    formCetakPeminjam.getTextAreaCetak().setText(dataPeminjam.toString());

    // Mengatur warna latar belakang dan teks
    formCetakPeminjam.getTextAreaCetak().setBackground(new java.awt.Color(176, 190, 197)); // Latar belakang abu-abu terang
    formCetakPeminjam.getTextAreaCetak().setForeground(new java.awt.Color(51, 51, 51)); // Teks hitam
    formCetakPeminjam.getTextAreaCetak().setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12)); // Font monospaced

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TABELTAMPILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELTAMPILMouseClicked
                                            
     // TODO add your handling code here:
    }//GEN-LAST:event_TABELTAMPILMouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        Dashboard pindah = new Dashboard();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        datauser pindah = new datauser();
        pindah.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        datapenyewa pindah = new datapenyewa();
        pindah.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        bayarbulanan pindah = new bayarbulanan();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        sewakamar pindah = new sewakamar();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // Membuat instance dari FrameB
        Dashboard pindah = new Dashboard();
        // Menutup jendela
        dispose();
        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        datakamar pindah = new datakamar();
        pindah.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44MouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameMouseClicked

    private void levelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_levelMouseClicked

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaMouseClicked

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roleMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        buktibayar pindah = new buktibayar();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        pembukuan pindah = new pembukuan();
        pindah.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // Membuat instance dari FrameB
        login pindah = new login();

        // Menampilkan pesan konfirmasi
        JOptionPane.showMessageDialog(null, "Anda yakin untuk keluar.");

        // Menutup jendela
        dispose();

        // Menampilkan FrameB
        pindah.setVisible(true);

        // Menutup FrameA (frame saat ini)
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembukuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABELTAMPIL;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel level;
    private javax.swing.JLabel pengguna;
    private javax.swing.JLabel role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    
    
    private void tampilDataSewa() {
    try {
        // Query untuk mengambil semua data dari tbbulanan
        String sql = "SELECT idsewa, nama_penyewa, tanggalsewa, nokamar, bulan, harga, created_at FROM tbbulanan";

        // Siapkan Statement
        Statement stmt = con.createStatement();
        
        // Eksekusi query
        ResultSet rs = stmt.executeQuery(sql);

        // Buat model untuk JTable
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Sewa");
        model.addColumn("Nama Penyewa");
        model.addColumn("Tanggal Sewa");
        model.addColumn("Nomor Kamar");
        model.addColumn("Bulan");
        model.addColumn("Harga Sewa");

        // Loop untuk membaca data dari ResultSet
        while (rs.next()) {
            Object[] row = new Object[7];
            row[0] = rs.getString("idsewa");
            row[1] = rs.getString("nama_penyewa");
            row[2] = rs.getDate("tanggalsewa");
            row[3] = rs.getString("nokamar");
            row[4] = rs.getString("bulan");
            row[5] = rs.getBigDecimal("harga");
            model.addRow(row);
        }

        // Set model ke JTable
        TABELTAMPIL.setModel(model);

        // Log hasil
        System.out.println("Data sewa berhasil dimuat.");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + e.getMessage());
    }

    }

  
    
    private void loadData() {
       PreparedStatement pstmt = null;
     ResultSet rs = null;

     try {
         // Pastikan koneksi sudah diinisialisasi
         if (con == null) {
             KoneksiDB koneksiDB = new KoneksiDB();
             koneksiDB.koneksikoskosan();
             con = koneksiDB.con;
         }

         // Query untuk mengambil data berdasarkan username dari session
         String sql = "SELECT * FROM akun WHERE username = ?";
         pstmt = con.prepareStatement(sql);
         pstmt.setString(1, login.Session.getUsername()); // Gunakan username dari session
         rs = pstmt.executeQuery();

         if (rs.next()) {
             // Set data ke TextField
             username.setText(rs.getString("username"));
             level.setText(rs.getString("level"));

             // Set ikon foto ke JLabel
             String fotoPath = rs.getString("foto"); 
                 if (fotoPath != null && !fotoPath.trim().isEmpty()) {
                     ImageIcon icon = new ImageIcon(fotoPath);
                     java.awt.Image img = icon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); // Dimensi tetap
                     foto.setIcon(new ImageIcon(img));
                 } else {
                     foto.setIcon(null);
                 }

         } else {
             // Menampilkan pesan bahwa pengguna harus login
             JOptionPane.showMessageDialog(this, "Silakan keluar dan login akun Anda!");
             login pindah = new login();
             pindah.setVisible(true);
             this.dispose();  
         }
//        
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
     } finally {
         try {
             if (rs != null) rs.close();
             if (pstmt != null) pstmt.close();
         } catch (Exception e) {
             e.printStackTrace();
         }
     }
//      
    }

    
}
